// Code generated by api-metadata-extractor. DO NOT EDIT.

package server

import (
	"time"

	"github.com/rprakashg/cac/internal/apimetadata"
)
const (
	API_RESOURCE_POLICIES = "policies"
)
const (
	API_ACTION_CREATE = "create"
	API_ACTION_DELETE = "delete"
	API_ACTION_GET = "get"
	API_ACTION_LIST = "list"
	API_ACTION_PATCH = "patch"
	API_ACTION_UPDATE = "update"
)
// timePtr is a helper to create time.Time pointers
func timePtr(year, month, day int) *time.Time {
	t := time.Date(year, time.Month(month), day, 0, 0, 0, 0, time.UTC)
	return &t
}

// ServerURLPrefixes lists normalized OpenAPI server URL path prefixes.
var ServerURLPrefixes = []string{
	"/api/v3",
}

// APIMetadataMap provides endpoint metadata keyed by "METHOD:/path"
// Uses pointers to avoid copy allocations on return
var APIMetadataMap = map[string]*apimetadata.EndpointMetadata{
	"GET:/policies": {
		OperationID: "listPolicies",
		Resource:    "policies",
		Action:      "list",
		Versions: []apimetadata.EndpointMetadataVersion{
			{Version: "1.0.12", DeprecatedAt: nil},
		},
	},
	"POST:/policies": {
		OperationID: "createPolicy",
		Resource:    "policies",
		Action:      "create",
		Versions: []apimetadata.EndpointMetadataVersion{
			{Version: "1.0.12", DeprecatedAt: nil},
		},
	},
	"DELETE:/policies/{name}": {
		OperationID: "deletePolicyByName",
		Resource:    "policies",
		Action:      "delete",
		Versions: []apimetadata.EndpointMetadataVersion{
			{Version: "1.0.12", DeprecatedAt: nil},
		},
	},
	"GET:/policies/{name}": {
		OperationID: "getPolicyByName",
		Resource:    "policies",
		Action:      "get",
		Versions: []apimetadata.EndpointMetadataVersion{
			{Version: "1.0.12", DeprecatedAt: nil},
		},
	},
	"PATCH:/policies/{name}": {
		OperationID: "patchPolicy",
		Resource:    "policies",
		Action:      "patch",
		Versions: []apimetadata.EndpointMetadataVersion{
			{Version: "1.0.12", DeprecatedAt: nil},
		},
	},
	"PUT:/policies/{name}": {
		OperationID: "updatePolicy",
		Resource:    "policies",
		Action:      "update",
		Versions: []apimetadata.EndpointMetadataVersion{
			{Version: "1.0.12", DeprecatedAt: nil},
		},
	},
}

// MetadataResolver provides lookup for endpoint metadata.
// Use MetadataResolver.Resolve(r) to get metadata from an HTTP request.
var MetadataResolver = apimetadata.NewStaticResolver(ServerURLPrefixes, APIMetadataMap)

