// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1beta1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xce28bOZL/KrW9BzhetFq2kx3sCRjgHCeZDWaTGLFzh8PYWFDdJYljNtlDsmVrAn/3",
	"QxXZD0ktWzOX5HA7/mfX6iZZD9bjV1U9+ZzkpqyMRu1dMvmcuHyBpeA/T6fOqNrjufAL+l2gy62svDQ6",
	"mSQfsbLoaBsIDSKuhZlUCJXwiyxJk8qaCq2XyOdVg+dcLrDbTUvAGxDhHKPBLxDcynksM3hvPIJfCA9C",
	"rwDvpPNSz8PSW6kUTBHMEu2tld6jJg7wTpSVIvo/JeOlsGNl5mNRVZky8+Q6TfyqwmSSOG+lnif39+0T",
	"M/0Zc5/cp8lpJf8TrWNuN5k/PX8b30GBM6nRMcPL8AwLCOoEMwO/kA5sozRBB9BjoSGQyuACLW0EtzC1",
	"KiA3eonWg8XczLX8tT3NkYaIjBIenQepPVotFCyFqjEFoQsoxQos0rlQ694JvMRl8M5YBKlnZgIL7ys3",
	"GY/n0mc3f3OZNOPclGWtpV+Nc6O9ldPaG+vGBS5RjZ2cj4TNF9Jj7muLY1HJETOrSSiXlcWfLTpT2xwd",
	"34GuS9L/8niKXhwnaZKLPLOVFTfCLeZEsHm1dSNpcjeam9HGNaXJmSkrJYXO8cILXwf7WrO2PK7w27f2",
	"0hiFQoPUhcwF25AXdo4epIN2H4i5kNr5cHPnRsl8tW5R3taYzoRy2PE9DWcPm9KZ0YX00ZKEUh9myeSn",
	"z8m/WZwlk+TP484Vx/Gqx+2Wl8Jhcp9uihlo7HnGJS0mziz+UkuLBV0Ln3C9xe11uqG19hSyTE+qgQK9",
	"kMrBzFgwGkG4iiyOrR0hr61F7cF54bF1gdPzt/Axmke2phSWcPuyhEOiGGk7b2s2O5gZpcwtXd6P9RSt",
	"Ro/h9L4twidHscEvgNXNsaUoQABxKmcyBxIbyES3A5YSzl9aoV1QnixxOHzROvCyxCB2y6tv92IBM2tK",
	"VpJjg2VOtPELtER4ZmwpfDJJCuFxRGclW8EpTUp0TswHuPh7XQoNFkUhpgohrusbeHNVYmpqHzlu2cuG",
	"iJmpo4BU/IAarfCD8Y+kz0r0ohBeZPN2ZYjS69q4FQ4cepgKhwXUVSDbCi61/+5FxwcFtTnahI1VuMHg",
	"C8+mVuLsEMIKNsM1mgduL0ldG0L28qIYcTb9KJ6SDplNK0R3h9cPxYcuqK2LHJ63DtYsT9mwzAwuKSLB",
	"GwpJKXzSN9rc6n4IpvdJmvCCJE3iiuGwS3tGS2G1KEP+3OAunrXxtDl643FLqS/lZYxdGzZFDmlmPcuR",
	"Gs5EiepMOOxLc25NZeZs30mavNYzY3P6+3rgjl/r3BRSz4dpXoRoENM3xrUhNtRkrmRaZOMbGbzPTaWE",
	"pAsm+/7uxZ46bdg6j5ub3y/jIcy5l371o9TFNt/0lJKWgEAk5PeOSRZigfDx9cUlNEk5xOFgdd1S1wEQ",
	"Ag9Sz9CGlRy5gl6KykgdHVtJDu71tJSekM0vNTpPcS2DM6G18QTH6ooCWpHB2/4dfm34QYp3oxupizUA",
	"0ubw8Mc/pPN7XlPV7Ax/KN55nyZvpMIzoz0OwYzL4KL0kpEeA9XtLJM/tJ+NCjzeeXj26fLN6G+HYCwE",
	"ExuxnWLRJ0I305DZ8oG4rrGxxwLemssM4hkS/12M/tv801tok8OW3HNr6mpYapLgwAGvSJtUjQWgpHwJ",
	"ggye7oZ0oesSrczh7asMXuFM1IqNEK4Sa4y/SrY10cOUI3cjq5Fh2kKN2LrRJhNCdpRvTYEPclihLaVj",
	"/E9rM/hvU7P7BJ5XfB8lGftMlFJJYcHkXqgISUCh4EDzK1oDzzCbZykcfffiBd8yi1lgLsu4gTL38J4X",
	"J0eH5L++lsXYoZ/T/3mZ36xgSt4pLIKrq8rY4IwzIP9sFZsynxvCcMwjOQnndXol9rLBPF07Ut0D2jK3",
	"Gu1Xvc9kknxyyH679zXvMmzKCfvj9H4kIJT+2NrWbR5bvFaF0+I+5uCSunXsIRR/nyYU54jc9t00byA8",
	"nqJr/TUgOLfSfoFe5m3ycFDWzsNCLDEFqXNVszFSRHRceS6FlaZ2DcwNjLgMTrv8Qw5CB4DRatVAl88f",
	"eCWxk0LD2P1wuJS6HvDLd2JFKYcwpgyRkCySfwtQspS+aSjoupyiJarSY0nJy9dWkx+QBBE1MxiIKJaR",
	"sIWFcMGbWUNiKaQivJ0BGXlIvZRZK/FLjW0ZPo0QwhuQzvELhv1Nymyq+V52Jc0z9g4JmJRLqyx6K3EZ",
	"ygxNOYFko9TScNKp+yyoie5GUIJw0nGO4LOIrZigK+OcpJ1RZVHS3OiZnNcRzZPc+ULoORbkoqwCvxCa",
	"chreQil1TeriO62EcxRjSCXNjTc9kplEVbTahtsFaqhdAClceoerjapsWjqyoNSeC9VoKmpax2xnHcEY",
	"VxlNqLfWCp2DlakDPxZzlK0qvblBHRCN0IDWkjgBkQ+mTIulkFrq+VuP5Zmpd+XpzqJcPXV0sdpH44p8",
	"suJvFzJfcDQm9Qf3wSIsaS66EYXDdLuzMZZYe2MBSkxRAcdo0qpDhTnhJA7mm3beytEw5aAOkJztNCiS",
	"jmmUrnDmodbsPLoAU0rvsYCiZpjp0Eqh5K8BBK8x2rRQ0CM8iwF+irmoHYLk1yR6vqj1DZ1kuresAuli",
	"a8vFRYedPBaj6oIFbsoUBCHA+vslaSCwUQXDX6FheZwd/xUKE1Im+h6NYOWUTDRdIwkRMdi23ZBkf0Hn",
	"ZckFy1+Ct8lfMWDD3Ci6P2bijKF12wgkuhY5Uu4625sm8lEJzD/wTuR+rwp7KAF2wXjb3rt3JNN6whBK",
	"EY7gaFP0kgZAP28EN4jm73hTDFwcsmOOyS0KPwCYubjg+wo/i1AmCnU+0Bnr+fK6FN3i0JVYteFP5v1Y",
	"0OmE+YkVvfOi3AFe20ZQrLBuKXiyKMX+nZ4CFf4eWtHmeftvoTd/oMlzCiGg5W1AWasve720XgMo+kGB",
	"jrBK6AFmcG6qWpEmWn3H1v5HFMWI4MCePSEOfv+b638nKo7WoWy+wVWDXlTdJP5c6H7yNnYuNPkrrSN8",
	"MDeWfj5zuanC0xCDD9ssPGRFjE2Hcwgj4FnvPof7coSih26pV98LT2DbNUOH8JzwGlwlVBaPidZVAkHT",
	"OzLfWu4eIKgbpBOVyGRDsm5bKQFOHLjekCJigbXZR7LXJCbW71utfrE2oXkQTHcr71PWxONFcNt94QZs",
	"V+w+tKsXPu/TxMVK4qEdQTauOfbuSMY9w+3InlKipD32r3dql5siX0zDnJiH6w4ygFdIwZb9pF35uMBJ",
	"ZxvCWrHqX+VTe+y3t8cGxgz7WXlbWD7grU0VvX4xP5glRQNKKaGj1mmfnWUz5RfSUXkTr5ibAsmEJ2+b",
	"cf2/UDDkjAVFMyVsyEgH7VnbMzvyoLl5TOyPODdtgyDUCFhITnun+Y4UmoepCCMzL7gGMZRH2529NiVy",
	"I5vSNJmALffsUW5v2wwJ24ymSU8bLPvuyLBrJtH7ECDW/IF+wAFh3jTfvO+hsj7k8QEK7cCgN0CPWZLy",
	"S4CCAUYPzh3FNv3W3vaOPd3sdiD87DtB2hhaD/rNmnltRWKpldSPTnz75jkMOPpggy6+0Uth8rpE7ffL",
	"yB9RCS+Xe3wiQhUML/3tX4icDuz9wp+GOJuPpS7wLvvZ7flZyCMjOhlk9rXVMeuQw+dCqYguC6MPfLMi",
	"NIR6sPHLpN98sH99Uc/nyPXZ3y8vzxsW8qbly5EzGHQKRyBnTeG7Cc2fnwxC86dU/EVT8Y6J/yks6lLo",
	"UTvz771u/Nr1psXcl4zF2Q68v2vKXop8ITXuJHW7WG0QoIuOba+r5I2QqrZUbQR+YrtIuq5jimXlV7HD",
	"ww2i9RTS9VlPqVB0RkOuhA1VhtDBjKOwbMbTmvwLQ6uJ3N7KAkH6R6b/D83aO+XBB25YT+AquajzHJ27",
	"SsDYvqRf3WwIJI2ELkZRpYPR+rFqoP1ggcPEXp8okLowr630qwuKOG14+ucNrkJ6SibJAkWBNmlST/u+",
	"y5uV/BE5cVbonTcW/ynqEPpnytyGREe5MpdcjNBLKrb5Aj5ZRTSiVpsDnmfuVsznaEm/hjaMm10kG9fo",
	"fC5Z8YR2JRP+G1amtsAP0oTSAzZvS1PI2YpfkTXzOpHn3AS+7+cEInQSHuFdKHNfmdwNTUR1AYSHuH8Z",
	"oNFFYDtJk3pNsE4cLqT0zDTTD5GzUrAUUgVlehTlf/Q/qNvud1zG5qoAx2kvdvhBRJcJETV+nBOT64cK",
	"9en5W3ieHbc9nugDPOjMhYbZtkhXOsoEwsNP2/JcP9t+dpjBlb7SF6bkhsusVqCkvnGTKz2Cny4XCB14",
	"Ip7PiGeLlXHSG7vqjpxLv6inWW7KcauQcS7yw/agmFpIMP5mM3xj0nw7dI4eLsigHj9yPFVmOi6F1GPC",
	"D/yHqOQ4NxbHy2OhqoU4HpsKtahkthKlOkzSRMkcdfjQLbrHaSXyBcJJdrRlBLe3t5ng15mx83Hc68b/",
	"eHv2+v3F69FJdpQtfKkYk6It3YfZRehgDlrSmNeMyRGlV7Smuanc6L562STiKGjUt4MkTZYNEkmOs6Ps",
	"+IR7UkHIZJI8z45ZDgJp7AFjBpbNzB/9jm6AUGqrXKNNfHaIvG+LuPi8e1kJK0r0aB1PaAc6VKE3CO1C",
	"KsJ+qdGumiGC4wlzCx2C1P2RXswAfAIdwM3pUvh80ZtGxUUHzQzrIE4hYhqsLC55LLo+4uFiLZkkzFAX",
	"MNsZZxq/xx5oaN6nQ33aMAMKw0JamftuMsNjoDh6a9rtoQ0rbZgmufWROy7RrvxC6vkuRnnXRaT6Dbll",
	"3bq0+aaBB0lsJsaSim8QDr4/SOHge/pfoQs4+NP3B83HElfJDa6Ov+d7O05vcHXyp/Dj5Co53CUpU/x9",
	"kpIlleJOlnW5NpELhtcK2Z8TdjPAy24my3VMGEDtNrS17QTe16ycC6Nw6MawlZA0z9mm2PtAQ7ie40hN",
	"2aMbb7KGdlqGLKVf09OjpcP9NXedmXOOFidHRxsfSImKQAFHg/HPEa52FB5vHXJ3kxP1xkjrR4piL74g",
	"vbbC36L1UhTwMdQggejxNyD6SbdoqAhUn38Dqm+MncqiQC5GX5z8+zcgeWkMvBN61ajYEem/fhNpY+aF",
	"T7qtWELrQMz7HxFeE+w1biARnvGUcLNDtZUCw7L2Y8ZYz740xeoLe0sQsisj4ldxGz56/FWoDmmmeHLS",
	"r+6kR9/CSc+MnikZ+mh/0LBwnyZ3o9bFJ0kLeO/TDjKPP1M2vQ+RQqEf6AO94ucPNLi3wkfYEXzt5ep9",
	"+FTyQRz9vtcrfpAQA4H4TWLEAfFTzPUg8hB8+pogYPclNQDgD+PmL74ByffGwxtTh9H5U/rv0v9gGfyx",
	"+brzoXEVlUDRpda9+gf0f0iX3o0Znlz6yaW/skuf9xC98PnA7PKc20Tit+Rn3tKi+ycvfgL9/4qh46nO",
	"+L9sP9QD+OMTD8DBWIh9iOCU7X+svxWowoanSLUWqZ76IU+h8Sk0/v8NjTuaMvzhA39zxMFtfUq79c/Z",
	"iEqOl8/531CJJLb+G5omkjowejMMui72Rc7ur+//JwAA//9zZ6qfqUkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
