// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1beta1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x7bW8jN5L/V6nl/gGPF62W7ZkN9i8gwDnOzO4gOzvG2HOHQ2wsqO6SxJhNdki2bGXg",
	"736oIvtBUttWcsm8ujeJ1U2yHlgPv6rq+SIKW9XWoAlezL4IX6ywkvzn+dxb3QS8lGFFv0v0hVN1UNaI",
	"mfiEtUNP20AakGktLJRGqGVY5SITtbM1uqCQz6tHz7leYb+blkCwIOM51kBYIfiND1jl8C8bEMJKBpBm",
	"A/igfFBmGZfeK61hjmDX6O6dCgENcYAPsqo10f9RTNfSTbVdTmVd59ouxW0mwqZGMRM+OGWW4vGxe2Ln",
	"P2ERxGMmzmv1n+g8c7vL/Pnl+/QOSlwog54ZXsdnWEJUJ9gFhJXy4FqlSTqAHksDkVQOV+hoI/iVbXQJ",
	"hTVrdAEcFnZp1C/daZ40RGS0DOgDKBPQGalhLXWDGUhTQiU34JDOhcYMTuAlPocP1iEos7AzWIVQ+9l0",
	"ulQhv/ubz5WdFraqGqPCZlpYE5yaN8E6Py1xjXrq1XIiXbFSAYvQOJzKWk2YWUNC+bwq/+zQ28YV6PkO",
	"TFOR/tencwzyVGSikEXuaifvpF8tiWD7au9GMvEwWdrJzjVl4sJWtVbSFHgVZGiifW1ZW5FWhP1b+85a",
	"jdKAMqUqJNtQkG6JAZSHbh/IpVTGh3hzl1arYrNtUcE1mC2k9tjzPY9nj5vShTWlCsmSpNYfF2L24xfx",
	"/xwuxEz8edq74jRd9bTb8p30KB6zXTEjjQPPuKbFxJnDnxvlsKRr4RNu97i9zXa01p1ClhlINVBikEp7",
	"WFgH1iBIX5PFsbUjFI1zaAL4IAN2LnB++R4+JfPIt5TCEu5flvRIFBNtH1zDZgcLq7W9p8v7oZmjMxgw",
	"nj60RfjsKTaEFbC6ObaUJUggTtVCFUBiA5nofsDS0odrJ42PylMVjocvWgdBVRjF7ngN3V4sYeFsxUry",
	"bLDMibFhhY4IL6yrZBAzUcqAEzpL7AWnTFTovVyOcPGPppIGHMpSzjVCWjc08Paq5Nw2IXHcsZePEbNz",
	"TwGp/DsadDKMxj+SPq8wyFIGmS+7lTFKb2vjXnrwGGAuPZbQ1JFsJ7gy4Zs3PR8U1JboBBur9KPBF17N",
	"ncLFMcQVbIZbNI/8QZL6LoQc5EUp4uz6UTolGzObToj+Dm+fiw99UNsWOT7vHKxdnrFh2QVcU0SCdxSS",
	"Mvhs7oy9N8MQTO9FJniByERaMR52ac9kLZ2RVcyfO9yls3aetkfvPO4oDaW8TrFrx6bIIe1iYDnKwIWs",
	"UF9Ij0NpLp2t7ZLtW2TirVlYV9DftyN3/NYUtlRmOU7zKkaDlL4xrY2xoSFzJdMiG9/J4ENuai0VXTDZ",
	"9zdvDtRpy9Zl2tz+/i4dwpwHFTY/KFPu801PKWlJiERifu+ZZCFWCJ/eXl1Dm5RjHI5W1y/1PQAh8KDM",
	"Al1cyZEr6qWsrTLJsbXi4N7MKxUI2fzcoA8U13K4kMbYQHCsqSmglTm8H97hHw0/SPF+cqdMuQVAuhwe",
	"//in8uHAa6rbnfEPzTsfM/FOabywJuAYzLiOLkovGekxUN3PMsVz+9moIOBDgFefr99N/nYM1kE0sQnb",
	"KZZDInQzLZk9H0jrWht7KeBtucwoniHxP6Tov88/vYUuOezJvXS2qcelJgmOPPCKrE3VWAIqypcgyeDp",
	"bkgXpqnQqQLef5/D97iQjWYjhBvhrA03Yl8TA0w58XeqnlimLfWErRudmBGyo3xrS3yWwxpdpTzjf1qb",
	"w3/bht0n8rzh+6jI2BeyUlpJB7YIUidIAholB5pf0Fl4hfkyz+Dkmzdv+JZZzBILVaUNlLnH97w5Ozkm",
	"/w2NKqcew5L+F1Rxt4E5ead0CL6pa+uiMy6A/LNTbMZ87gjDMY/kJJzX65XYy0fzdONJdc9oy94bdH/o",
	"fYqZ+OyR/fbga37KsCknHI7Th5GAUPpLazu3eWnxVhVOi4eYg0vqzrHHUPxjJijOEbn9u2nfQHw8R9/5",
	"a0RwfmPCCoMquuThoWp8gJVcYwbKFLphY6SI6LnyXEunbONbmBsZ8Tmc9/mHHIQOAGv0poUuXz7ySmIn",
	"g5axx/FwqUwz4pcf5IZSDmFMFSMhWST/lqBVpULbUDBNNUdHVFXAipJXaJwhPyAJEmpmMJBQLCNhByvp",
	"ozezhuRaKk14Owcy8ph6KbPW8ucGuzJ8niBEsKC85xcM+9uU2Vbzg+xKmmfsHRMwKZdWOQxO4TqWGYZy",
	"AslGqaXlpFf3RVQT3Y2kBOGV5xzBZxFbKUHX1ntFO5PKkqSFNQu1bBKaJ7mLlTRLLMlFWQVhJQ3lNLyH",
	"SpmG1MV3WkvvKcaQStobb3skC4W67LQN9ys00PgIUrj0jlebVNm2dFRJqb2QutVU0rRJ2c55gjG+toZQ",
	"b2M0eg8b20R+HBaoOlUGe4cmIhppAJ0jcSIiH02ZDiupjDLL9wGrC9s8lad7i/LN3NPFmpCMK/HJir9f",
	"qWLF0ZjUH90Hy7ikvehWFA7T3c7WWFLtjSVoOUcNHKNJqx41FoSTOJjv2nknR8uUhyZCcrbTqEg6plW6",
	"xkWAxrDzmBJspULAEsqGYaZHp6RWv0QQvMVo20LBgPAqBfg5FrLxCIpfk+jFqjF3dJLt37IKlE+tLZ8W",
	"HffyOEyqixa4K1MUhADrb5ekhcBWlwx/pYH1aX76VyhtTJkYBjSilVMyMXSNJETCYPt2Q5L9BX1QFRcs",
	"f4nepn7BiA0Lq+n+mIkLhtZdI5DoOuRI+dTZwbaRj0pg/oEPsggHVdhjCbAPxvv23r8jmbYThtSacARH",
	"m3KQNACGeSO6QTJ/z5tS4OKQnXJM4VCGEcDMxQXfV/xZxjJR6suRztjAl7el6BfHrsSmC3+qGMaCXifM",
	"T6rofZDVE+C1awSlCuuegieLUh7e6SlR42+hlWyet/8aestnmjznEANa0QWUrfpy0EsbNICSH5ToCavE",
	"HmAOl7ZuNGmi03dq7X9CWU4IDhzYE+Lg97+5/g+y5mgdy+Y73LToRTdt4i+kGSZv65bSkL/SOsIHS+vo",
	"5ytf2Do+jTH4uMvCY1bE2HQ8hzACXgzuc7wvRyh67JYG9b0MBLZ9O3SIzwmvwY2gsnhKtG4ERE0/kfm2",
	"cvcIQdMinaREJhuTdddKiXDiyA+GFAkLbM0+xEGTmFS/77X65daE5lkw3a98zFgTLxfBXfeFG7B9sfvc",
	"rkH4fMyET5XEczuibFxzHNyRTHvG25EDpSRJB+zfPqldbor8bhrmxDxed5ABfI8UbNlPupUvCyx625DO",
	"yc0fe5Vd9fSMSbal4raUf7drMnmKm7Ft1HsoW8RuXiuVJwyf2nxc+YoZj5d2g9d/oWRclVBzOwprySgP",
	"3Vn7gykyk6V9SexPuLRdFRyBMJaKY/t58USeKGLrn+FHkAy0LSWLbuegF4fcraVcpOiv6sBG3P62Xbvf",
	"ZzQTA22w7E+b/1ON98G0OxW2kX5MdnGosty977HaNSarEQpdV3wwJU6pgIJoxDsRK44O16iIb6HLQc7U",
	"DyNH/OnQkcjOFHbUR7ZMaS+0KKOVeXGEOTTF8Qw6zJ50ya0zlLZoKjThsBTzCbUMan3ANw8EyXnpr//k",
	"4Xxk7+/8rYN3xVSZEh/yn/yB3zm8MHNSUWYq3VMBTs5dSK0TXCqtOQrtitjhGOCg3yefFKMN2atmuUQu",
	"OP5xfX3ZslC0PUyOktGgMzgBtWgruV2s+fpsFGve/d/o5TePXg4fYZ/DqqmkmXRD7MHr1q/9YPzJjbZU",
	"bTwBYJ8aG1eyWCmDT5K6X212CNBFpz7OjXgnlW4cwefIT+p/KN+3ALGqwya1LLjjsZ0u+sbhOVU+3hoo",
	"tHQRNksTzTgJy2Y8b8i/MPZOyO2dKhFUeGGc/dzwuFcefOQO7AxuxFVTFOj9jQDrhpL+4WZDgGgiTTlJ",
	"Kh2N1i/B224Cz2HioJk7qQuLxqmwuaKI04Wnf9/hJqYnMRMrlCU60aae7n2fN2v1A3LirDH4YB3+WzYx",
	"9C+0vY+JjnJloRhd00uqHvkCPjtNNJJW2wNe5/5eLpfoSL+WNkzbXSQbF518LlnxjHaJGf8NG9s44AeZ",
	"oPSA7dvKlmqx4VdkzbxOFgV3NR+HOYEIncVH+BDrtu9t4cdGfKYEwj7ckIsw6CqyLTLRbAnWi8OVgVnY",
	"tp0vC1YKVlLpqMyAsvqP4Rdi+wX8deoWSvCc9lLLGmRymRhR09cmKbl+rNGcX76H1/lp17RIPsCTO6r4",
	"F/si3ZgkE8gAP+7Lc/tq/9lxDjfmxlzZijsIi0aDVubOz27MBH6kcr8HT8TzBfHssLZeBes2/ZFLFVbN",
	"PC9sNe0UMi1kcdwdlFILCcYfIcaPJtqPYS4xwBUZ1MtHTufazqeVVGZK+IH/kLWaFtbhdH0qdb2Sp1Nb",
	"o5G1yjey0sciE1oVaOKXW8k9zmtZrBDO8pM9I7i/v88lv86tW07TXj/95/uLt/+6ejs5y0/yVag0Y1J0",
	"lf+4uIotuVFLmvKaKTmiCprWtDdVWDNUL5tEmm1MhnYgMrFukYg4zU/y0zNuskQhxUy8zk9YDgJp7AFT",
	"BpbtEBvDE+Wt1HqvNKNNfHaMvO/LtPiyf1lLJysM6DyPHEdaLrHZBd1CKrh+btBt2q6455FpBx2i1MMZ",
	"VcoAfAIdwN3WSoZiNRivpEVH7VDmKLXVUxqsHa55zrc9s+DCTMwEM9QHzG5ol6UPjEc6dI/ZWOMxDjXi",
	"9ItWFqEfNfBcI82S2v5x7CsqF8cjfnuGjGt0m7BSZvkUo7zrKlH9ityybn3WDul5MsJmYh2p+A7h6Nuj",
	"DI6+pf9KU8LRn749aqf/N+ION6ff8r2dZne4OftT/HF2I46fkpQp/jZJyZIq+aCqptoaMUXD64QcDr76",
	"odZ1P2TkOiZOVJ42tK3tBN63rJwLo3jozvSQkDQPjuY4+OJA+oHjKEPZo5/XsYaetAxVqbClpxdLh8db",
	"bqMy5xwtzk5Odr74kTWBAo4G058SXO0pvNwL43YdJ+qdGc0PFMXe/I70ugp/j9Z3soRPsQaJRE+/AtHP",
	"pkNDZaT6+itQfWfdXJUlcjH65uz/fwWS19bCB2k2rYo9kf7rV5E2ZV74bLqKJbYO5NIPvqe7Jdhr/Ugi",
	"vOCx1273cy8FxmXd13kDlzGN1o+ZeJh0e2eiy6SPWZ+Lp1/ITR/F7EuE9FxNcwbdxh97//KA8M36NX/u",
	"nsTaFeJtlzQSwGXcPJ7afwVa3oJGe/A4BZ224X37+D8BAAD//xXnGryoMwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
