// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1beta1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xce28bOZL/KrW9BzhetFq2kx3sCRjgHCeZDWaTGLFzh8PYWFDdJYljNtlDsmVrAn/3",
	"QxXZD0ktWzOX5HA7/mfX6iZZD9bjV1U9+ZzkpqyMRu1dMvmcuHyBpeA/T6fOqNrjufAL+l2gy62svDQ6",
	"mSQfsbLoaBsIDSKuhZlUCJXwiyxJk8qaCq2XyOdVg+dcLrDbTUvAGxDhHKPBLxDcynksM3hvPIJfCA9C",
	"rwDvpPNSz8PSW6kUTBHMEu2tld6jJg7wTpSVIvo/JeOlsGNl5mNRVZky8+Q6TfyqwmSSOG+lnif39+0T",
	"M/0Zc5/cp8lpJf8TrWNuN5k/PX8b30GBM6nRMcPL8AwLCOoEMwO/kA5sozRBB9BjoSGQyuACLW0EtzC1",
	"KiA3eonWg8XczLX8tT3NkYaIjBIenQepPVotFCyFqjEFoQsoxQos0rlQ694JvMRl8M5YBKlnZgIL7ys3",
	"GY/n0mc3f3OZNOPclGWtpV+Nc6O9ldPaG+vGBS5RjZ2cj4TNF9Jj7muLY1HJETOrSSiXlcWfLTpT2xwd",
	"34GuS9L/8niKXhwnaZKLPLOVFTfCLeZEsHm1dSNpcjeam9HGNaXJmSkrJYXO8cILXwf7WrO2PK7w27f2",
	"0hiFQoPUhcwF25AXdo4epIN2H4i5kNr5cHPnRsl8tW5R3taYzoRy2PE9DWcPm9KZ0YX00ZKEUh9myeSn",
	"z8m/WZwlk+TP484Vx/Gqx+2Wl8Jhcp9uihlo7HnGJS0mziz+UkuLBV0Ln3C9xe11uqG19hSyTE+qgQK9",
	"kMrBzFgwGkG4iiyOrR0hr61F7cF54bF1gdPzt/Axmke2phSWcPuyhEOiGGk7b2s2O5gZpcwtXd6P9RSt",
	"Ro/h9L4twidHscEvgNXNsaUoQABxKmcyBxIbyES3A5YSzl9aoV1QnixxOHzROvCyxCB2y6tv92IBM2tK",
	"VpJjg2VOtPELtER4ZmwpfDJJCuFxRGclW8EpTUp0TswHuPh7XQoNFkUhpgohrusbeHNVYmpqHzlu2cuG",
	"iJmpo4BU/IAarfCD8Y+kz0r0ohBeZPN2ZYjS69q4FQ4cepgKhwXUVSDbCi61/+5FxwcFtTnahI1VuMHg",
	"C8+mVuLsEMIKNsM1mgduL0ldG0L28qIYcTb9KJ6SDplNK0R3h9cPxYcuqK2LHJ63DtYsT9mwzAwuKSLB",
	"GwpJKXzSN9rc6n4IpvdJmvCCJE3iiuGwS3tGS2G1KEP+3OAunrXxtDl643FLqS/lZYxdGzZFDmlmPcuR",
	"Gs5EiepMOOxLc25NZeZs30mavNYzY3P6+3rgjl/r3BRSz4dpXoRoENM3xrUhNtRkrmRaZOMbGbzPTaWE",
	"pAsm+/7uxZ46bdg6j5ub3y/jIcy5l371o9TFNt/0lJKWgEAk5PeOSRZigfDx9cUlNEk5xOFgdd1S1wEQ",
	"Ag9Sz9CGlRy5gl6KykgdHVtJDu71tJSekM0vNTpPcS2DM6G18QTH6ooCWpHB2/4dfm34QYp3oxupizUA",
	"0ubw8Mc/pPN7XlPV7Ax/KN55nyZvpMIzoz0OwYzL4KL0kpEeA9XtLJM/tJ+NCjzeeXj26fLN6G+HYCwE",
	"ExuxnWLRJ0I305DZ8oG4rrGxxwLemssM4hkS/12M/tv801tok8OW3HNr6mpYapLgwAGvSJtUjQWgpHwJ",
	"ggye7oZ0oesSrczh7asMXuFM1IqNEK4Sa4y/SrY10cOUI3cjq5Fh2kKN2LrRJhNCdpRvTYEPclihLaVj",
	"/E9rM/hvU7P7BJ5XfB8lGftMlFJJYcHkXqgISUCh4EDzK1oDzzCbZykcfffiBd8yi1lgLsu4gTL38J4X",
	"J0eH5L++lsXYoZ/T/3mZ36xgSt4pLIKrq8rY4IwzIP9sFZsynxvCcMwjOQnndXol9rLBPF07Ut0D2jK3",
	"Gu1Xvc9kknxyyH679zXvMmzKCfvj9H4kIJT+2NrWbR5bvFaF0+I+5uCSunXsIRR/nyYU54jc9t00byA8",
	"nqJr/TUgOLfSfoFe5m3ycFDWzsNCLDEFqXNVszFSRHRceS6FlaZ2DcwNjLgMTrv8Qw5CB4DRatVAl88f",
	"eCWxk0LD2P1wuJS6HvDLd2JFKYcwpgyRkCySfwtQspS+aSjoupyiJarSY0nJy9dWkx+QBBE1MxiIKJaR",
	"sIWFcMGbWUNiKaQivJ0BGXlIvZRZK/FLjW0ZPo0QwhuQzvELhv1Nymyq+V52Jc0z9g4JmJRLqyx6K3EZ",
	"ygxNOYFko9TScNKp+yyoie5GUIJw0nGO4LOIrZigK+OcpJ1RZVHS3OiZnNcRzZPc+ULoORbkoqwCvxCa",
	"chreQil1TeriO62EcxRjSCXNjTc9kplEVbTahtsFaqhdAClceoerjapsWjqyoNSeC9VoKmpax2xnHcEY",
	"VxlNqLfWCp2DlakDPxZzlK0qvblBHRCN0IDWkjgBkQ+mTIulkFrq+VuP5Zmpd+XpzqJcPXV0sdpH44p8",
	"suJvFzJfcDQm9Qf3wSIsaS66EYXDdLuzMZZYe2MBSkxRAcdo0qpDhTnhJA7mm3beytEw5aAOkJztNCiS",
	"jmmUrnDmodbsPLoAU0rvsYCiZpjp0Eqh5K8BBK8x2rRQ0CM8iwF+irmoHYLk1yR6vqj1DZ1kuresAuli",
	"a8vFRYedPBaj6oIFbsoUBCHA+vslaSCwUQXDX6FheZwd/xUKE1Im+h6NYOWUTDRdIwkRMdi23ZBkf0Hn",
	"ZckFy1+Ct8lfMWDD3Ci6P2bijKF12wgkuhY5Uu4625sm8lEJzD/wTuR+rwp7KAF2wXjb3rt3JNN6whBK",
	"EY7gaFP0kgZAP28EN4jm73hTDFwcsmOOyS0KPwCYubjg+wo/i1AmCnU+0Bnr+fK6FN3i0JVYteFP5v1Y",
	"0OmE+YkVvfOi3AFe20ZQrLBuKXiyKMX+nZ4CFf4eWtHmeftvoTd/oMlzCiGg5W1AWasve720XgMo+kGB",
	"jrBK6AFmcG6qWpEmWn3H1v5HFMWI4MCePSEOfv+b638nKo7WoWy+wVWDXlTdJP5c6H7yNnYuNPkrrSN8",
	"MDeWfj5zuanC0xCDD9ssPGRFjE2Hcwgj4FnvPof7coSih26pV98LT2DbNUOH8JzwGlwlVBaPidZVAkHT",
	"OzLfWu4eIKgbpBOVyGRDsm5bKQFOHLjekCJigbXZR7LXJCbW71utfrE2oXkQTHcr71PWxONFcNt94QZs",
	"V+w+tKsXPu/TxMVK4qEdQTauOfbuSMY9w+3InlKipD32r3dql5siX0zDnJiH6w4ygFdIwZb9pF35uMBJ",
	"ZxvCWrHqX+VTe+y3t8cGxgz7WXlbWD7grU0VvX4xP5glRQNKKaGj1mmfnWUz5RfSUXkTr5ibAsmEJ2+b",
	"cf2/UDDkjAVFMyVsyEgH7VnbMzvyoLl5TOyPODdtgyDUCFhITnun+Y4UmoepCCMzL7gGMZRH2529NiVy",
	"I5vSNJmALffsUW5v2wwJ24ymSU8bLPvuyLBrJtH7ECDW/IF+wAFh3jTfvO+hsj7k8QEK7cCgN0CPWZLy",
	"S4CCAUYPzh0FFNigur3iTDenHQg1+06LNgbUgz6yZkpbUVdqJfWj092+KQ6Diz6woEtunKEweV2i9vtl",
	"34+ohJfLPT4HoWqFl/72r0FOB/Z+4c9AnM3HUhd4l/3s9vwE5JFxnAwy+9rqmGHIuXOhVESShdEHvlkR",
	"mj89iPhlUm0+2Ku+qOdz5Frs75eX5w0LedPe5SgZDDqFI5CzpsjdhOHPTwZh+FPa/aJpd8d0/xQWdSn0",
	"qJ3v9143fu16k2HuQcZCbAe23zVRL0W+kBp3krpdrDYI0EXHFtdV8kZIVVuqLAI/sTUkXdcdxbLyq9jN",
	"4WbQerroeqqnVBQ6oyFXwoaKQuhgxlFYNuNpTf6Foa1Ebm9lgSD9I5P+h+bqnfLgAzenJ3CVXNR5js5d",
	"JWBsX9KvbjYEiEZCF6Oo0sFo/Rjybz9O4DCx1+cIpC7Mayv96oIiThue/nmDq5CekkmyQFGgTZrU077v",
	"8mYlf0ROnBV6543Ff4o6hP6ZMrch0VGuzCUXHvSSCmu+gE9WEY2o1eaA55m7FfM5WtKvoQ3jZhfJxvU4",
	"n0tWPKFdyYT/hpWpLfCDNKH0gM3b0hRytuJXZM28TuQ5N3zv+zmBCJ2ER3gXStpXJndD009dAGEf7lUG",
	"GHQR2E7SpF4TrBOHiyY9M82kQ+SsFCyFVEGZHkX5H/2P57Z7G5exkSrAcdqL3XwQ0WVCRI0f4sTk+qFC",
	"fXr+Fp5nx20/J/oADzVzoWG2LdKVjjKB8PDTtjzXz7afHWZwpa/0hSm5uTKrFSipb9zkSo/gp8sFQgee",
	"iOcz4tliZZz0xq66I+fSL+pplpty3CpknIv8sD0ophYSjL/PDN+TNN8JnaOHCzKox48cT5WZjksh9Zjw",
	"A/8hKjnOjcXx8lioaiGOx6ZCLSqZrUSpDpM0UTJHHT5qi+5xWol8gXCSHW0Zwe3tbSb4dWbsfBz3uvE/",
	"3p69fn/xenSSHWULXyrGpGhL92F2EbqVg5Y05jVjckTpFa1pbio3uq9eNok49hn17SBJk2WDRJLj7Cg7",
	"PuH+UxAymSTPs2OWg0Aae8CYgWUz30e/o/IXSm2VZrSJzw6R920RF593LythRYkereNp7EA3KvQBoV1I",
	"BdcvNdpVMzBwPE1uoUOQuj++ixmAT6ADuBFdCp8vepOnuOigmVcdxIlDTIOVxSWPQNfHOVyYJZOEGeoC",
	"ZjvPTOO31wPNy/t0qCcb5j1hMEgrc99NYXjkE8dsTWs9tFylDZMjtz5exyXalV9IPd/FKO+6iFS/Ibes",
	"W5c23y/w0IjNxFhS8Q3CwfcHKRx8T/8rdAEHf/r+oPkw4iq5wdXx93xvx+kNrk7+FH6cXCWHuyRlir9P",
	"UrKkUtzJsi7Xpm/B8Foh+zPBbt532c1fuY4Jw6bdhra2ncD7mpVzYRQO3RisEpLmmdoUex9jCNdzHKkp",
	"e3SjTNbQTsuQpfRrenq0dLi/5g4zc87R4uToaONjKFERKOBoMP45wtWOwuNtQu5kcqLeGF/9SFHsxRek",
	"11b4W7ReigI+hhokED3+BkQ/6RYNFYHq829A9Y2xU1kUyMXoi5N//wYkL42Bd0KvGhU7Iv3XbyJtzLzw",
	"SbcVS2gdiHn/g8Frgr3GDSTCM54IbnY/t1JgWNZ+uBjr2ZemWH1hbwlCdmVE/AJuw0ePvwrVIc0UT076",
	"1Z306Fs46ZnRMyVDH+0PGhbu0+Ru1Lr4JGkB733aQebxZ8qm9yFSKPQDfaBX/Hy7mb47fIQdwddert6H",
	"zyIfxNHve73iBwkxEIjfH0YcED+7XA8iD8GnrwkCdl9SAwD+MG7+4huQfG88vDF1GJM/pf8u/Q+WwR+b",
	"LznFA05GJVB0qXWv/gH9H9Kld2OGJ5d+cumv7NLnPUQvfD4wuzznNpH4LfmZt7To/smLn0D/v2LoeKoz",
	"/i/bD/UA/vjEA3AwFmIfIjhl+x/mbwWqsOEpUq1Fqqd+yFNofAqN/39D446mDH/4wN8ccXBbn9Ju/dM1",
	"opLj5XP+91Iiia3/XqaJpA6M3gyDrot9kbP76/v/CQAA///Oq3ZdlUkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
