// Package v1beta1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1beta1

import (
	"time"
)

// Defines values for ConditionStatus.
const (
	ConditionStatusFalse   ConditionStatus = "False"
	ConditionStatusTrue    ConditionStatus = "True"
	ConditionStatusUnknown ConditionStatus = "Unknown"
)

// Defines values for ConditionType.
const (
	Enforcing   ConditionType = "Enforcing"
	Propogating ConditionType = "Propogating"
)

// Defines values for EncodingType.
const (
	EncodingBase64 EncodingType = "base64"
	EncodingPlain  EncodingType = "plain"
)

// Defines values for EntityKind.
const (
	EntityKindPolicy     EntityKind = "Policy"
	EntityKindPolicylist EntityKind = "PolicyList"
)

// Defines values for PolicySpecRemediationAction.
const (
	Enforce PolicySpecRemediationAction = "enforce"
	Inform  PolicySpecRemediationAction = "inform"
)

// AbsolutePath Represents an absolute file path.
type AbsolutePath struct {
	// Path The absolute path to a file on the system. Note that any existing file will be overwritten.
	Path *string `json:"path,omitempty"`
}

// ApiVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources.
type ApiVersion = string

// ComplianceStatus defines model for ComplianceStatus.
type ComplianceStatus struct {
	// Compliant Boolean indicating target is compliant against this Policy
	Compliant *bool `json:"compliant,omitempty"`
}

// Condition defines model for Condition.
type Condition struct {
	// LastTransitionTime The last time the condition transitioned from one status to another.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message Human readable message indicating details about last transition.
	Message string `json:"message"`

	// ObservedGeneration The .metadata.generation that the condition was set based upon.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A (brief) reason for the condition's last transition.
	Reason string `json:"reason"`

	// Status Status of the condition, one of True, False, Unknown.
	Status ConditionStatus `json:"status"`

	// Type Type of condition in CamelCase.
	Type ConditionType `json:"type"`
}

// ConditionBase Base condition structure following Kubernetes API conventions. Use with allOf to add a specific type enum.
type ConditionBase struct {
	// LastTransitionTime The last time the condition transitioned from one status to another.
	LastTransitionTime time.Time `json:"lastTransitionTime"`

	// Message Human readable message indicating details about last transition.
	Message string `json:"message"`

	// ObservedGeneration The .metadata.generation that the condition was set based upon.
	ObservedGeneration *int64 `json:"observedGeneration,omitempty"`

	// Reason A (brief) reason for the condition's last transition.
	Reason string `json:"reason"`

	// Status Status of the condition, one of True, False, Unknown.
	Status ConditionStatus `json:"status"`
}

// ConditionStatus Status of the condition, one of True, False, Unknown.
type ConditionStatus string

// ConditionType Type of condition in CamelCase.
type ConditionType string

// EncodingType Specifies the encoding type used for data representation.
type EncodingType string

// EntityKind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds.
type EntityKind string

// FileContent The content of a file.
type FileContent struct {
	// Content The plain text (UTF-8) or base64-encoded content of the file.
	Content *string `json:"content,omitempty"`

	// ContentEncoding Specifies the encoding type used for data representation.
	ContentEncoding *EncodingType `json:"contentEncoding,omitempty"`
}

// FileMetadata File metadata.
type FileMetadata struct {
	// Group The file's group, specified either as a name or numeric ID. Defaults to "root".
	Group string `json:"group,omitempty"`

	// Mode The file's permission mode. You may specify the more familiar octal with a leading zero (e.g., 0644) or as a decimal without a leading zero (e.g., 420). Setuid/setgid/sticky bits are supported. If not specified, the permission mode for files defaults to 0644.
	Mode *int `json:"mode,omitempty"`

	// User The file's owner, specified either as a name or numeric ID. Defaults to "root".
	User Username `json:"user,omitempty"`
}

// FileSpec defines model for FileSpec.
type FileSpec struct {
	// Content The plain text (UTF-8) or base64-encoded content of the file.
	Content string `json:"content"`

	// ContentEncoding Specifies the encoding type used for data representation.
	ContentEncoding *EncodingType `json:"contentEncoding,omitempty"`

	// Group The file's group, specified either as a name or numeric ID. Defaults to "root".
	Group string `json:"group,omitempty"`

	// Mode The file's permission mode. You may specify the more familiar octal with a leading zero (e.g., 0644) or as a decimal without a leading zero (e.g., 420). Setuid/setgid/sticky bits are supported. If not specified, the permission mode for files defaults to 0644.
	Mode *int `json:"mode,omitempty"`

	// Path The absolute path to a file on the system. Note that any existing file will be overwritten.
	Path string `json:"path"`

	// User The file's owner, specified either as a name or numeric ID. Defaults to "root".
	User Username `json:"user,omitempty"`
}

// ListMeta ListMeta describes metadata that synthetic resources must have, including lists and various status objects. A resource may have only one of {ObjectMeta, ListMeta}.
type ListMeta struct {
	// Continue May be set if the user set a limit on the number of items returned, and indicates that the server has more data available. The value is opaque and may be used to issue another request to the endpoint that served this list to retrieve the next set of available objects. Continuing a consistent list may not be possible if the server configuration has changed or more than a few minutes have passed. The resourceVersion field returned when using this continue value will be identical to the value in the first response, unless you have received this token from an error message.
	Continue *string `json:"continue,omitempty"`

	// RemainingItemCount The number of subsequent items in the list which are not included in this list response. If the list request contained label or field selectors, then the number of remaining items is unknown and the field will be left unset and omitted during serialization. If the list is complete (either because it is not chunking or because this is the last chunk), then there are no more remaining items and this field will be left unset and omitted during serialization. Servers older than v1.15 do not set this field. The intended use of the remainingItemCount is *estimating* the size of a collection. Clients should not rely on the remainingItemCount to be set or to be exact.
	RemainingItemCount *int64 `json:"remainingItemCount,omitempty"`
}

// ObjectMeta ObjectMeta is metadata that all persisted resources    must have, which includes all objects users must create.
type ObjectMeta struct {
	// Annotations Properties set by the service.
	Annotations *map[string]string `json:"annotations,omitempty"`

	// CreationTimestamp The time the object was created.
	CreationTimestamp *time.Time `json:"creationTimestamp,omitempty"`

	// DeletionTimestamp The time the object will be deleted.
	DeletionTimestamp *time.Time `json:"deletionTimestamp,omitempty"`

	// Generation A sequence number representing a specific generation of the desired state. Populated by the system. Read-only.
	Generation *int64 `json:"generation,omitempty"`

	// Labels Map of string keys and values that can be used to organize and categorize (scope and select) objects.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name The name of the object.
	Name *string `json:"name,omitempty"`

	// Owner A resource that owns this resource, in "kind/name" format.
	Owner *string `json:"owner,omitempty"`

	// ResourceVersion An opaque string that identifies the server's internal version of an object.
	ResourceVersion *string `json:"resourceVersion,omitempty"`
}

// Policy defines model for Policy.
type Policy struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds.
	Kind EntityKind `json:"kind"`

	// Metadata ObjectMeta is metadata that all persisted resources    must have, which includes all objects users must create.
	Metadata ObjectMeta `json:"metadata"`

	// Spec Governance policy resource spec
	Spec *PolicySpec `json:"spec,omitempty"`

	// Status Represents status information about governance policy
	Status *PolicyStatus `json:"status,omitempty"`
}

// PolicyList defines model for PolicyList.
type PolicyList struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources.
	ApiVersion *ApiVersion `json:"apiVersion,omitempty"`

	// Items List of Devices.
	Items *[]Policy `json:"items,omitempty"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds.
	Kind *EntityKind `json:"kind,omitempty"`

	// Metadata ListMeta describes metadata that synthetic resources must have, including lists and various status objects. A resource may have only one of {ObjectMeta, ListMeta}.
	Metadata *ListMeta `json:"metadata,omitempty"`
}

// PolicySpec Governance policy resource spec
type PolicySpec struct {
	// Disabled Weather this compliance policy is disabled
	Disabled bool         `json:"disabled"`
	Rego     RegoFileSpec `json:"rego"`

	// RemediationAction Action to be taken for remediation
	RemediationAction PolicySpecRemediationAction `json:"remediationAction"`
}

// PolicySpecRemediationAction Action to be taken for remediation
type PolicySpecRemediationAction string

// PolicyStatus Represents status information about governance policy
type PolicyStatus struct {
	// Conditions Conditions represent the observations of a the current state of a device.
	Conditions *[]Condition      `json:"conditions,omitempty"`
	Status     *ComplianceStatus `json:"status,omitempty"`
}

// RegoFileSpec defines model for RegoFileSpec.
type RegoFileSpec struct {
	Inline *FileSpec `json:"inline,omitempty"`

	// Name name of the rego policy document
	Name *string `json:"name,omitempty"`
}

// RelativePath Represents a relative file path.
type RelativePath struct {
	// Path A relative file path on the system. Note that any existing file will be overwritten.
	Path *string `json:"path,omitempty"`
}

// Status Status is a return value for calls that don't return other objects.
type Status struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources.
	ApiVersion ApiVersion `json:"apiVersion"`

	// Code Suggested HTTP return code for this status, 0 if not set.
	Code int32 `json:"code"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds.
	Kind string `json:"kind"`

	// Message A human-readable description of the status of this operation.
	Message string `json:"message"`

	// Reason A machine-readable description of why this operation is in the "Failure" status. If this value is empty there is no information available. A Reason clarifies an HTTP status code but does not override it.
	Reason string `json:"reason"`

	// Status Status of the operation. One of: "Success" or "Failure". More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status.
	Status string `json:"status"`
}

// ListPoliciesParams defines parameters for ListPolicies.
type ListPoliciesParams struct {
	// Continue An optional parameter to query more results from the server. The value of the paramter must match the value of the 'continue' field in the previous list response.
	Continue *string `form:"continue,omitempty" json:"continue,omitempty"`

	// LabelSelector A selector to restrict the list of returned objects by their labels. Defaults to everything.
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`

	// FieldSelector A selector to restrict the list of returned objects by their fields, supporting operators like '=', '==', and '!=' (e.g., "key1=value1,key2!=value2").
	FieldSelector *string `form:"fieldSelector,omitempty" json:"fieldSelector,omitempty"`

	// Limit The maximum number of results returned in the list response. The server will set the 'continue' field in the list response if more results exist. The continue value may then be specified as parameter in a subsequent query.
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}
